In [1]:
import numpy as np
import random

In [5]:
x = np.arange(3)

In [6]:
len(x)

3

In [7]:
x

array([0, 1, 2])

In [9]:
yy = np.array([[1, 1], [2, 2], [3, 3]])
yy.shape

(3, 2)

In [22]:
#aa = np.matmul(x.reshape(1, -1), yy)
aa = np.matmul(x, yy)

In [24]:
print aa.shape
print aa
print aa.sum()

(2,)
[8 8]
16


#### two vector outer product

In [26]:
aa = np.arange(3)
bb = np.arange(2)

In [31]:
print aa.shape, bb.shape

(3,) (2,)


In [37]:
np.transpose(aa).shape

(3,)

In [40]:
cc = np.matmul(aa.reshape(len(aa), 1), bb.reshape(1, len(bb)))
print cc.shape
print cc

(3, 2)
[[0 0]
 [0 1]
 [0 2]]


#### check the multi-index stuff

In [44]:
aa = np.zeros([4, 3])

In [47]:
#aa[[1, 2]] = np.array([[3, 3, 3], [4, 4, 4]])
aa[[1, 2]] = [[3, 3, 3], [4, 4, 4]]
print aa

[[ 0.  0.  0.]
 [ 3.  3.  3.]
 [ 4.  4.  4.]
 [ 0.  0.  0.]]


In [48]:
aa

array([[ 0.,  0.,  0.],
       [ 3.,  3.,  3.],
       [ 4.,  4.,  4.],
       [ 0.,  0.,  0.]])

In [ ]:
np.log(1.)

In [26]:
aa = np.zeros(5)
aa[2] = 1

In [27]:
aa

array([ 0.,  0.,  1.,  0.,  0.])

In [17]:
x = x.reshape(4, 1)

In [18]:
x.T.shape

(1, 4)

In [19]:
x.shape

(4, 1)

In [5]:
xx = x.reshape(4, 1)

In [20]:
xx = np.random.rand(4, 2)

In [21]:
xx

array([[ 0.81801638,  0.6377167 ],
       [ 0.76205853,  0.46495717],
       [ 0.52801006,  0.91492024],
       [ 0.16205028,  0.19815989]])

In [22]:
np.matmul(x.T, xx)

array([[ 2.3042295 ,  2.88927734]])

In [25]:
tmp = xx + y
tmp.shape

(4, 5)

In [26]:
tmp

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.]])

In [7]:
y = np.ones(5)
z = np.ones((3, 4))

In [9]:
z

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [27]:
tmp - np.amax(tmp, axis=1).reshape((tmp.shape[0], 1))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [31]:
tmp

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.]])

In [29]:
np.exp(tmp)

array([[  2.71828183,   2.71828183,   2.71828183,   2.71828183,
          2.71828183],
       [  7.3890561 ,   7.3890561 ,   7.3890561 ,   7.3890561 ,   7.3890561 ],
       [ 20.08553692,  20.08553692,  20.08553692,  20.08553692,
         20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003,
         54.59815003]])

In [32]:
np.sum(tmp, axis=1)

array([  5.,  10.,  15.,  20.])

#### check the `sigmoid` function

In [18]:
rndstate = random.getstate()

In [22]:
(rndstate)

(3,
 (2147483648L,
  3825722852L,
  3423508426L,
  4248033027L,
  2097757886L,
  433988641L,
  481062745L,
  2461311606L,
  3407900201L,
  144514326L,
  2960930209L,
  1488727961L,
  225531695L,
  755564246L,
  2128058733L,
  2622389340L,
  1195289316L,
  456368364L,
  2663620456L,
  759368535L,
  319192370L,
  1557185433L,
  3556377473L,
  1317303775L,
  1896599745L,
  4253662011L,
  366074714L,
  554558712L,
  4063547538L,
  1195729401L,
  3683363332L,
  610961739L,
  1118315268L,
  3628417161L,
  3454879328L,
  3159573949L,
  1444747361L,
  1268560922L,
  1095972090L,
  659060115L,
  3935466036L,
  1073595213L,
  2127840068L,
  522059434L,
  1144466660L,
  1611038319L,
  1981671946L,
  2353061408L,
  754569138L,
  4172084713L,
  3735359122L,
  1709694879L,
  214872233L,
  2880276289L,
  1669076112L,
  2620670060L,
  2857287276L,
  1475930604L,
  2736693376L,
  2094171516L,
  1446637627L,
  1630269772L,
  3266637133L,
  1504502778L,
  1675384960L,
  4157024626L,
  1206182007L,
  3722

In [10]:
np.exp(0)

1.0