### understand Tensorflow basic operations on the constant

In [1]:
import numpy as np
import tensorflow as tf

#### create the softmax in TensorFlow

In [35]:
sess = tf.InteractiveSession()
inputs = tf.constant(np.array([[1001, 1002], [3, 4]]))
row_max = tf.reduce_max(inputs, 1)
row_max = tf.reshape(row_max, [inputs.shape[0].value, 1])
exp_x = tf.exp(tf.to_float(inputs - row_max))
row_exp_sum = tf.reduce_sum(exp_x, 1)
out = exp_x / row_exp_sum
print out.eval()
#row_max = tf.reshape(, [inputs.shape[0], 1])
#row_max = tf.constant(tf.reduce_max(inputs, 1), shape=)
#exp_x = tf.exp(inputs. - row_max)
#print(exp_x.eval())
sess.close()
                              

[[ 0.26894143  0.7310586 ]
 [ 0.26894143  0.7310586 ]]


#### try the boolean mask

In [48]:
inputs = tf.constant(np.array([[0., 1002.], [3., 0.]]))
#zero = tf.constant(0, dtype=tf.float64)
boolean_mask = tf.equal(inputs, 0.)
boolean_mask = tf.to_float(boolean_mask) * 1E-9
print boolean_mask.eval()


[[  9.99999972e-10   0.00000000e+00]
 [  0.00000000e+00   9.99999972e-10]]


In [2]:
random_num = np.random.rand(2, 3, 4)

In [3]:
random_num

array([[[ 0.04524727,  0.33377906,  0.89476474,  0.83266262],
        [ 0.22051281,  0.07657816,  0.20222046,  0.20336211],
        [ 0.80924396,  0.68478933,  0.69294016,  0.02292009]],

       [[ 0.42256813,  0.90166277,  0.90175484,  0.09649898],
        [ 0.52047075,  0.95096625,  0.66740198,  0.89025909],
        [ 0.57504036,  0.24302295,  0.71615617,  0.45741952]]])

In [16]:
#vector = np.random.rand(5)
#vector = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.arange(2, 5)

In [17]:
print vector.shape
vector

(3,)


array([2, 3, 4])

In [24]:
matrix = np.array([[2, 2, 2], [3, 3, 3]])

In [25]:
print matrix.shape
matrix

(2, 3)


array([[2, 2, 2],
       [3, 3, 3]])

In [18]:
vector.reshape([1, -1]).shape
#vector.reshape([-1, 1])

(1, 3)

In [22]:
matrix + vector

array([[4, 5, 6],
       [5, 6, 7]])