In [21]:
import numpy as np

In [22]:
data = np.array(range(10))

In [23]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
cumsum = np.cumsum(data)

In [25]:
cumsum

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [26]:
cumsum[:-n]

array([ 0,  1,  3,  6, 10, 15, 21])

In [16]:
n = 3
cumsum[n:] = cumsum[n:] - cumsum[:-n]

In [17]:
cumsum

array([ 0,  1,  3,  6,  9, 12, 15, 18, 21, 24])

In [19]:
cumsum[n-1:] / n

array([1, 2, 3, 4, 5, 6, 7, 8])