In [2]:
import tensorflow as tf

#### start the iteractive session

In [3]:
sess = tf.InteractiveSession()

#### test the argmax

In [10]:
aa = tf.constant([[2, 1, 3], [3, 6, 2]])
max_index = tf.constant([2, 2])

In [19]:
index = tf.argmax(aa, axis=1, output_type=tf.int32)

In [20]:
max_index.eval()

array([2, 2], dtype=int32)

In [21]:
index.eval()

array([2, 1], dtype=int32)

In [23]:
correct_prediction = tf.reduce_mean(tf.cast(tf.equal(index, max_index), tf.float32))

In [26]:
correct_prediction.eval()

0.5

#### check the slide function

In [11]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]],
                 [[3, 3, 3], [4, 4, 4]],
                 [[5, 5, 5], [6, 6, 6]]])

In [13]:
t.shape, t.eval()

(TensorShape([Dimension(3), Dimension(2), Dimension(3)]), array([[[1, 1, 1],
         [2, 2, 2]],
 
        [[3, 3, 3],
         [4, 4, 4]],
 
        [[5, 5, 5],
         [6, 6, 6]]], dtype=int32))

#### understand the `slice` function: 
 1. first arguement `offset` provides an array for offset value for each dimension
 2. second arguemnt `size`: a. `size` dimension is the same dimension as sliced data; b. size[i] is the length for i-th dimension

In [14]:
res = tf.slice(t, [1, 0, 0], [1, 2, 3]) 

In [15]:
res.eval()

array([[[3, 3, 3],
        [4, 4, 4]]], dtype=int32)